### ISSUE TITLE
Using Distinct for collections with null element throws ArgumentNullException 

### ISSUE THREAD

**Issue by atifaziz** [atifaziz/LINQBridge#13]
```
What steps will reproduce the problem?
[Test]
public void NullElementCollection()
{
            var list = new List<string>();
            list.Add(null);
            Assert.AreEqual(list.Distinct().ToList()[0], null);
}

What version of the product are you using? On what operating system?
r239    
```

Original issue reported on code.google.com by `alec.che...@gmail.com` on 22 Apr 2010 at 12:32

**Comment by atifaziz** [comment]
```
Added suggested test (see patch) and it effectively fails with the following 
exception:

System.ArgumentNullException : Value cannot be null.
Parameter name: key
at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
at System.Linq.Enumerable.<DistinctYield>d__6c`1.MoveNext() in Enumerable.cs: 
line 834
at 
LinqBridge.Tests.EnumerableFixture.Distinct_StringArrayWithOneNull_YieldsSet() 
in EnumerableFixture.cs: line 512 
```

Original comment by `azizatif` on 19 Oct 2010 at 9:17
- Changed state: **Accepted**

Attachments:
- [issue-13-test.patch](https://storage.googleapis.com/google-code-attachments/linqbridge/issue-13/comment-1/issue-13-test.patch)

**Comment by atifaziz** [comment]
```
Fixed in r240.
```

Original comment by `azizatif` on 19 Oct 2010 at 9:49
- Changed state: **Fixed**

**Comment by atifaziz** [comment]
Original comment by `azizatif` on 16 Nov 2010 at 10:11
- Added labels: **Milestone-Release1.2**
